name: gs-view
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - cuda-toolkit=12.4
  - pytorch-cuda=12.4
  - vs2022_win-64
  - pytorch
  - click
  - glfw
  - imageio-ffmpeg
  - imageio
  - munch
  - numpy<2
  - opencv
  - pandas
  - pillow
  - plyfile
  - pydantic
  - pyopengl
  - requests
  - scipy
  - tqdm

  - pip:
    - gaussian-splatting/submodules/diff-gaussian-rasterization
    - gaussian-splatting/submodules/simple-knn
    - imgui_bundle==1.5.2
    - imgui==2.0.0
    - scikit-image==0.24
    - imagecodecs[all]==2024.6.1
    - pynvml
    - GPUtil
